server:
  port: 8080
  servlet:
    context-path: /car_service_booking
spring:
  application:
    name: identity-service  
  datasource:
    url: jdbc:postgresql://localhost:5432/car_service_booking
    username: postgres
    password: 171104
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true